/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LOT_PB_H_INCLUDED
#define PB_LOT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Device status (per-report system metrics) */
typedef struct _DeviceStatus {
    uint32_t device_id; /* from Kconfig LOT_PROTO_DEVICE_ID */
    int64_t ts; /* unix timestamp (NTP), 0 if unavailable */
    uint32_t uptime_s; /* seconds since boot */
    uint32_t heap_free; /* current free heap (bytes) */
    uint32_t heap_min; /* historical minimum free heap (bytes) */
    int32_t rssi; /* Wi-Fi RSSI (dBm) */
    char fw_ver[16]; /* firmware version string */
} DeviceStatus;

/* One sensor / Modbus data point */
typedef struct _SensorPoint {
    uint32_t ch; /* channel index or Modbus register address */
    float value; /* scaled engineering value */
    uint32_t alarm; /* 0=OK  1=high  2=low */
} SensorPoint;

/* Top-level uplink frame */
typedef struct _UplinkMsg {
    uint32_t msg_id; /* monotonic counter, used for dedup / ACK */
    bool has_status;
    DeviceStatus status;
    pb_size_t sensors_count;
    SensorPoint sensors[8];
} UplinkMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DeviceStatus_init_default                {0, 0, 0, 0, 0, 0, ""}
#define SensorPoint_init_default                 {0, 0, 0}
#define UplinkMsg_init_default                   {0, false, DeviceStatus_init_default, 0, {SensorPoint_init_default, SensorPoint_init_default, SensorPoint_init_default, SensorPoint_init_default, SensorPoint_init_default, SensorPoint_init_default, SensorPoint_init_default, SensorPoint_init_default}}
#define DeviceStatus_init_zero                   {0, 0, 0, 0, 0, 0, ""}
#define SensorPoint_init_zero                    {0, 0, 0}
#define UplinkMsg_init_zero                      {0, false, DeviceStatus_init_zero, 0, {SensorPoint_init_zero, SensorPoint_init_zero, SensorPoint_init_zero, SensorPoint_init_zero, SensorPoint_init_zero, SensorPoint_init_zero, SensorPoint_init_zero, SensorPoint_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define DeviceStatus_device_id_tag               1
#define DeviceStatus_ts_tag                      2
#define DeviceStatus_uptime_s_tag                3
#define DeviceStatus_heap_free_tag               4
#define DeviceStatus_heap_min_tag                5
#define DeviceStatus_rssi_tag                    6
#define DeviceStatus_fw_ver_tag                  7
#define SensorPoint_ch_tag                       1
#define SensorPoint_value_tag                    2
#define SensorPoint_alarm_tag                    3
#define UplinkMsg_msg_id_tag                     1
#define UplinkMsg_status_tag                     2
#define UplinkMsg_sensors_tag                    3

/* Struct field encoding specification for nanopb */
#define DeviceStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,         1) \
X(a, STATIC,   SINGULAR, INT64,    ts,                2) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_s,          3) \
X(a, STATIC,   SINGULAR, UINT32,   heap_free,         4) \
X(a, STATIC,   SINGULAR, UINT32,   heap_min,          5) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              6) \
X(a, STATIC,   SINGULAR, STRING,   fw_ver,            7)
#define DeviceStatus_CALLBACK NULL
#define DeviceStatus_DEFAULT NULL

#define SensorPoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ch,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2) \
X(a, STATIC,   SINGULAR, UINT32,   alarm,             3)
#define SensorPoint_CALLBACK NULL
#define SensorPoint_DEFAULT NULL

#define UplinkMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   msg_id,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            2) \
X(a, STATIC,   REPEATED, MESSAGE,  sensors,           3)
#define UplinkMsg_CALLBACK NULL
#define UplinkMsg_DEFAULT NULL
#define UplinkMsg_status_MSGTYPE DeviceStatus
#define UplinkMsg_sensors_MSGTYPE SensorPoint

extern const pb_msgdesc_t DeviceStatus_msg;
extern const pb_msgdesc_t SensorPoint_msg;
extern const pb_msgdesc_t UplinkMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DeviceStatus_fields &DeviceStatus_msg
#define SensorPoint_fields &SensorPoint_msg
#define UplinkMsg_fields &UplinkMsg_msg

/* Maximum encoded size of messages (where known) */
#define DeviceStatus_size                        63
#define LOT_PB_H_MAX_SIZE                        UplinkMsg_size
#define SensorPoint_size                         17
#define UplinkMsg_size                           223

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
